server:
  port: 8989
spring:
  datasource:
    url: jdbc:mysql://123.60.186.69:3306/sg_blog?useSSL=false&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 5MB
  main:
    allow-circular-references: true
#  redis:
#    host: 192.168.43.210
#    port: 6379
#    timeout: 3
#    # password:
#    pool:
#      minIdle: 1
#      maxIdle: 10
#      maxWait: 3
#      maxActive: 8
  redis:
    host: 123.60.186.69
    port: 6379
    timeout: 0
    # password:
    #    pool:
    #    minIdle: 1
    #    maxIdle: 10
    #    maxWait: 3
    #    maxActive: 8
    jedis:
      pool:
        max-active: 50    # 连接池最大连接数（使用负值表示没有限制）
        max-wait: 5000    # 连接池中连接用完时，新的请求等待时间(毫秒)，超过该时间抛出异常JedisConnectionException，(默认-1，负值表示没有限制，不建议使用默认值)
        max-idle: 10      # 连接池中的最大空闲连接，默认8
        min-idle: 1       # 连接池中的最小空闲连接，默认0
        time-between-eviction-runs: 30000
mybatis-plus:
  configuration:
    # 日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto
  mapper-locations: mapper/*.xml
